apiVersion: v1
kind: Secret                            # Secret stores sensitive key-value data
metadata:
  name: ecommerce-secret                # The name used to reference this Secret
type: Opaque                            # Generic key-value secret (default type)
stringData:
  MYSQL_USER: ecommerce_user            # MySQL username
  MYSQL_PASSWORD: ecommerce_pass        # MySQL password
  RABBITMQ_USER: ecommerce_mq_user      # RabbitMQ username
  RABBITMQ_PASSWORD: ecommerce_mq_pass  # RabbitMQ password
