apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
        - name: ecommerce
          image: shihabmi7/ecommerce-api:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: ecommerce-secret

